"""modify column name

Revision ID: a71b14542d42
Revises: 
Create Date: 2022-03-24 10:26:26.565529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71b14542d42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('an_contact', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('an_contact_created_by_fkey', 'an_contact', type_='foreignkey')
    op.create_foreign_key(None, 'an_contact', 'users', ['user_id'], ['id'])
    op.drop_column('an_contact', 'created_by')
    op.alter_column('image_type', 'name',
               existing_type=sa.CHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image_type', 'name',
               existing_type=sa.CHAR(length=255),
               nullable=True)
    op.add_column('an_contact', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'an_contact', type_='foreignkey')
    op.create_foreign_key('an_contact_created_by_fkey', 'an_contact', 'users', ['created_by'], ['id'])
    op.drop_column('an_contact', 'user_id')
    # ### end Alembic commands ###
